/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef AMPSUMOFAMPLITUDES
#define AMPSUMOFAMPLITUDES

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooListProxy.h"

#include "AmpAbsDynamicalFunction.hpp"
#include "AmpWigner.hpp"

class TIterator;
class RooRealVar;
 
class AmpSumOfAmplitudes : public RooAbsPdf {
public:
  AmpSumOfAmplitudes();
  AmpSumOfAmplitudes(const char *name, const char *title);
  AmpSumOfAmplitudes(const AmpSumOfAmplitudes& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new AmpSumOfAmplitudes(*this,newname); }
  virtual ~AmpSumOfAmplitudes();

  void addBW(AmpAbsDynamicalFunction*, RooRealVar&, RooRealVar&);
  void addBW(AmpAbsDynamicalFunction*, RooRealVar&, RooRealVar&, AmpWigner*);

  Double_t evaluateSlice(RooComplex*, unsigned int, unsigned int) const ;
  Double_t evaluate() const ;
  
protected:

private:
  RooListProxy _pdfList ;   //  List of component PDFs
  RooListProxy _intList;    //  List of relative intensities
  RooListProxy _phaseList;  //  List of relative phases
  RooListProxy _angList ;   //  List of component angular distributions

  TIterator* _pdfIter  ;
  TIterator* _intIter  ;
  TIterator* _phaseIter;
  TIterator* _angIter;

  //ClassDef(AmpSumOfAmplitudes,1) // Your description goes here...
};
 
#endif
